name: deployment

on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  ARTIFACT_NAME: serverless-1.0-SNAPSHOT.jar
  FUNCTION_NAME: user-create-verification
  AWS_REGION: us-east-1
  PYTHON_WD: lambda_python

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: package python to zip file
        run: |
          zip ${{ env.PYTHON_WD }}/${{ env.FUNCTION_NAME }}.zip ${{ env.PYTHON_WD }}/${{ env.FUNCTION_NAME }}.py

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.GH_ACTION_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GH_ACTION_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: deploy .zip file to lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.FUNCTION_NAME }} \
            --zip-file fileb://${{ env.PYTHON_WD }}/${{ env.FUNCTION_NAME }}.zip
